server:
  port: ${PAYMENT_SERVICE_PORT:8085}

spring:
  config:
    import:
      - "optional:file:.env[.properties]"
      - "optional:file:../.env[.properties]"
      - "optional:file:payment-service/.env[.properties]"

  application:
    name: payment-service

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/connecthub_payment?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:12345678}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

  boot:
    admin:
      client:
        url: http://${ADMIN_SERVER_HOST:localhost}:${ADMIN_SERVER_PORT:8089}
        username: ${ADMIN_USER:admin}
        password: ${ADMIN_PASSWORD:admin_password}

jwt:
  secret: ${JWT_SECRET:fUfwkEaeomu7puBOIl0ftR50UPF4CBPUDxZ0lcaGXL2hY3Zai4DS4YO7l4902IJsKVdHyNjdpCL4LX7IGkw2qg==}

eureka:
  client:
    service-url:
      defaultZone: http://eureka:eureka@${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
  instance:
    prefer-ip-address: true

razorpay:
  key-id: ${RAZORPAY_KEY_ID}
  key-secret: ${RAZORPAY_KEY_SECRET}
  webhook-secret: ${RAZORPAY_WEBHOOK_SECRET}
  pro-plan-id: ${RAZORPAY_PRO_PLAN_ID:}

mail:
  host: ${MAIL_HOST:smtp.gmail.com}
  port: ${MAIL_PORT:587}
  username: ${MAIL_USERNAME:}
  password: ${MAIL_PASSWORD:}

aws:
  access-key: ${AWS_ACCESS_KEY_ID:}
  secret-key: ${AWS_SECRET_ACCESS_KEY:}
  region: ${AWS_REGION:}
  bucket: ${AWS_S3_BUCKET:}

management:
  health:
    redis:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers,env
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
